CORE_LOGGER_NAME_STR = "n_elastic_ip_pool"
DEFAULT_TIMEOUT_SECOND_INT = 10
MAX_ELASTIC_IP_FAILURE_COUNT_INT = 3
ELASTIC_IP_HEALTH_CHECK_URL_STR = "https://example.com/health"
DEFAULT_PROXY_COUNTRY_CODE_STR = "US"
ELASTIC_IP_STATUS_ACTIVE_STR = "active"
ELASTIC_IP_STATUS_FAILED_STR = "failed"
ELASTIC_IP_STATUS_UNAVAILABLE_STR = "unavailable"
